name: Continuous Integration

on:
  push:
    branches:
      - main  # Run on every push to the main branch
  pull_request:  # Run on pull requests to validate changes
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Deno
      - name: Set Up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      # Step 3: Validate TypeScript files
      - name: TypeScript Type-Checking
        run: |
          deno lint
          deno check ./marduk-ts/**/*.ts

      # Step 4: Run Tests
      - name: Run Tests
        run: deno test ./marduk-ts/tests/

